<div class="space-y-5">
    <header class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel">
        <h1 class="text-2xl font-black text-slate-900">{{ __('calendar.admin.title') }}</h1>
        <p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">{{ __('calendar.admin.description') }}</p>
    </header>

    @if (! $schemaReady)
        <div class="rounded-panel border border-amber-200 bg-amber-50 p-5 text-sm text-amber-900" role="status">{{ __('calendar.unavailable') }}</div>
    @else
        @if ($notice)<div class="rounded-control border border-emerald-200 bg-emerald-50 p-4 text-sm font-bold text-emerald-800" role="status">{{ $notice }}</div>@endif
        <form wire:submit="save" class="rounded-panel border border-slate-200 bg-white p-4 shadow-panel sm:p-6" aria-labelledby="calendar-admin-form-title">
            <h2 id="calendar-admin-form-title" class="text-lg font-black text-slate-900">{{ $editingPublicId ? __('calendar.admin.edit_entry') : __('calendar.admin.create_entry') }}</h2>
            <div class="mt-5 grid gap-4 lg:grid-cols-2 xl:grid-cols-3">
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.search_title') }}</span><input type="search" wire:model.live.debounce.300ms="titleSearch" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.title_target') }}</span><select wire:model.live="catalogTitleId" required class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2"><option value="">{{ __('calendar.admin.select_title') }}</option>@foreach ($titles as $title)<option value="{{ $title->id }}">{{ $title->display_title }}</option>@endforeach</select>@error('catalogTitleId')<span class="mt-1 block text-xs text-rose-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.season_target') }}</span><select wire:model.live="seasonId" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2"><option value="">{{ __('calendar.admin.no_season') }}</option>@foreach ($seasons as $season)<option value="{{ $season->id }}">{{ __('calendar.season_number', ['number' => $season->number]) }}{{ $season->title ? ' · '.$season->title : '' }}</option>@endforeach</select></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.episode_target') }}</span><select wire:model.live="episodeId" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2"><option value="">{{ __('calendar.admin.no_episode') }}</option>@foreach ($episodes as $episode)<option value="{{ $episode->id }}">{{ __('calendar.episode_number', ['number' => $episode->number]) }}{{ $episode->title ? ' · '.$episode->title : '' }}</option>@endforeach</select></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.media_target') }}</span><select wire:model="licensedMediaId" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2"><option value="">{{ __('calendar.admin.no_media') }}</option>@foreach ($mediaOptions as $media)<option value="{{ $media->id }}">#{{ $media->id }} · {{ $media->quality ?: __('calendar.admin.quality_unknown') }} · {{ $media->translation_name ?: __('calendar.admin.translation_unknown') }}</option>@endforeach</select></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.entry_type') }}</span><select wire:model="entryType" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2">@foreach ($typeOptions as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.status') }}</span><select wire:model="status" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2">@foreach ($statusOptions as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select>@error('status')<span class="mt-1 block text-xs text-rose-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.precision') }}</span><select wire:model="precision" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2">@foreach ($precisionOptions as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.source') }}</span><select wire:model="source" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3 py-2">@foreach ($sourceOptions as $option)<option value="{{ $option->value }}">{{ $option->label() }}</option>@endforeach</select></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.datetime') }}</span><input type="datetime-local" wire:model="startsAt" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.date') }}</span><input type="date" wire:model="dateValue" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" />@error('dateValue')<span class="mt-1 block text-xs text-rose-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.date_end') }}</span><input type="date" wire:model="dateEnd" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.year') }}</span><input type="number" min="1900" max="2200" wire:model="releaseYear" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.month') }}</span><input type="number" min="1" max="12" wire:model="releaseMonth" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.quarter') }}</span><input type="number" min="1" max="4" wire:model="releaseQuarter" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.timezone') }}</span><input type="text" wire:model="originalTimezone" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" />@error('originalTimezone')<span class="mt-1 block text-xs text-rose-700" role="alert">{{ $message }}</span>@enderror</label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.language') }}</span><input type="text" wire:model="languageCode" maxlength="16" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.translation') }}</span><input type="text" wire:model="translationName" maxlength="120" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700 xl:col-span-2"><span>{{ __('calendar.admin.source_reference') }}</span><input type="text" wire:model="sourceReference" maxlength="191" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.reason') }}</span><input type="text" wire:model="reasonCode" maxlength="48" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2" /></label>
                <label class="text-sm font-bold text-slate-700 xl:col-span-2"><span>{{ __('calendar.admin.public_note') }}</span><textarea wire:model="publicNote" rows="3" class="mt-2 w-full rounded-control border border-slate-300 px-3 py-2"></textarea></label>
                <label class="text-sm font-bold text-slate-700"><span>{{ __('calendar.admin.private_note') }}</span><textarea wire:model="privateNote" rows="3" class="mt-2 w-full rounded-control border border-slate-300 px-3 py-2"></textarea></label>
            </div>
            <fieldset class="mt-5 grid gap-3 rounded-control bg-slate-50 p-4 sm:grid-cols-2 lg:grid-cols-4"><legend class="px-2 text-sm font-black text-slate-700">{{ __('calendar.admin.flags') }}</legend><label class="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" wire:model="isEstimated" class="h-5 w-5 rounded" />{{ __('calendar.admin.estimated') }}</label><label class="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" wire:model="isLocked" class="h-5 w-5 rounded" />{{ __('calendar.admin.locked') }}</label><label class="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" wire:model="isPublic" class="h-5 w-5 rounded" />{{ __('calendar.admin.public') }}</label><label class="flex min-h-11 items-center gap-3 text-sm font-bold"><input type="checkbox" wire:model="notificationsEnabled" class="h-5 w-5 rounded" />{{ __('calendar.admin.notifications') }}</label></fieldset>
            <div class="mt-5 flex flex-wrap gap-3"><button type="submit" wire:loading.attr="disabled" class="inline-flex min-h-11 items-center gap-2 rounded-control bg-emerald-700 px-5 text-sm font-bold text-white"><x-ui.icon name="fa-solid fa-floppy-disk" />{{ __('calendar.admin.save') }}</button>@if ($editingPublicId)<button type="button" wire:click="cancelEdit" class="min-h-11 rounded-control bg-slate-100 px-5 text-sm font-bold text-slate-700">{{ __('calendar.admin.cancel') }}</button>@endif<span wire:loading wire:target="save" class="self-center text-sm font-bold text-emerald-700" role="status">{{ __('calendar.loading') }}</span></div>
        </form>

        @if ($editingPublicId && $corrections->isNotEmpty())
            <section class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel" aria-labelledby="calendar-corrections-title">
                <h2 id="calendar-corrections-title" class="text-lg font-black text-slate-900">{{ __('calendar.admin.correction_history') }}</h2>
                <ol class="mt-4 space-y-3">@foreach ($corrections as $correction)<li wire:key="release-correction-{{ $correction->id }}" class="rounded-control bg-slate-50 p-4"><p class="text-sm font-black text-slate-800">r{{ $correction->revision }} · {{ $correction->new_status->label() }} · {{ $correction->new_precision->label() }}</p><p class="mt-1 text-xs text-slate-500">{{ $correction->actor?->name ?: __('calendar.admin.system_actor') }} · {{ $correction->created_at?->toAtomString() }}</p>@if ($correction->private_note)<p class="mt-2 break-words text-sm text-slate-700">{{ $correction->private_note }}</p>@endif</li>@endforeach</ol>
            </section>
        @endif

        <section class="overflow-hidden rounded-panel border border-slate-200 bg-white shadow-panel" aria-labelledby="calendar-admin-list-title">
            <h2 id="calendar-admin-list-title" class="p-5 text-lg font-black text-slate-900">{{ __('calendar.admin.entries') }}</h2>
            @if ($entries === null || $entries->isEmpty())<p class="border-t border-slate-100 p-5 text-sm text-slate-600">{{ __('calendar.empty.title') }}</p>@else<ul class="divide-y divide-slate-100">@foreach ($entries as $entry)<li wire:key="admin-release-{{ $entry->public_id }}" class="flex min-w-0 flex-wrap items-center justify-between gap-3 p-4"><div class="min-w-0"><p class="break-words text-sm font-black text-slate-800">{{ $entry->catalogTitle->display_title }}</p><p class="mt-1 text-xs text-slate-500">{{ $entry->entry_type->label() }} · {{ $entry->status->label() }} · {{ $entry->precision->label() }} · r{{ $entry->revision }}</p></div><button type="button" wire:click="edit('{{ $entry->public_id }}')" class="min-h-11 rounded-control bg-slate-100 px-4 text-sm font-bold text-slate-700">{{ __('calendar.admin.edit') }}</button></li>@endforeach</ul>@if ($entries->hasPages())<nav class="p-4">{{ $entries->links() }}</nav>@endif @endif
        </section>
    @endif
</div>
