@props(['issue', 'statusOptions', 'severityOptions', 'priorityOptions', 'resolutionOptions', 'teamOptions', 'assigneeOptions', 'rejectionOptions', 'rerouteOptions', 'sourceActionOptions', 'canResolve', 'canAssign'])

<x-ui.panel :title="__('issues.admin.actions')" icon="fa-solid fa-screwdriver-wrench">
    <div class="space-y-5">
        @if (count($issue->relatedTickets) > 0)<section aria-labelledby="related-technical-issues"><h3 id="related-technical-issues" class="font-black text-slate-900">{{ __('issues.admin.related') }}</h3><ul class="mt-2 space-y-2">@foreach ($issue->relatedTickets as $related)<li><a href="{{ $related['url'] }}" class="flex min-h-11 flex-wrap items-center justify-between gap-2 rounded-control bg-slate-50 px-3 text-sm font-bold text-emerald-700"><span>{{ $related['number'] }} · {{ $related['type'] }}</span><span class="text-slate-600">{{ $related['status'] }}</span></a></li>@endforeach</ul></section>@endif
        @if (count($statusOptions) > 0)<form wire:submit="applyStatus" class="space-y-3">
            <label for="admin-issue-status" class="block text-sm font-bold">{{ __('issues.fields.status') }}</label><select id="admin-issue-status" wire:model="desiredStatus" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($statusOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select>
            <label for="admin-public-reason" class="block text-sm font-bold">{{ __('issues.fields.public_update') }}</label><textarea id="admin-public-reason" wire:model="publicReason" rows="3" maxlength="2000" class="w-full rounded-control border border-slate-300 p-3"></textarea>
            <label for="admin-private-note" class="block text-sm font-bold">{{ __('issues.fields.private_note') }}</label><textarea id="admin-private-note" wire:model="privateNote" rows="3" maxlength="4000" class="w-full rounded-control border border-slate-300 p-3"></textarea>
            <label for="admin-rejection" class="block text-sm font-bold">{{ __('issues.fields.rejection_reason') }}</label><select id="admin-rejection" wire:model="rejectionReason" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($rejectionOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select>
            <label for="admin-reroute" class="block text-sm font-bold">{{ __('issues.fields.reroute') }}</label><select id="admin-reroute" wire:model="reroutedTo" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($rerouteOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select>
            <button type="submit" wire:loading.attr="disabled" class="min-h-11 rounded-control bg-slate-800 px-4 py-2 font-bold text-white">{{ __('issues.actions.apply_status') }}</button>
        </form>@else<p class="rounded-control bg-slate-50 p-3 text-sm text-slate-600">{{ __('issues.states.no_status_actions') }}</p>@endif

        <form wire:submit="classify" class="grid gap-3 border-t border-slate-100 pt-4 sm:grid-cols-2">
            <div><label for="admin-severity" class="block text-sm font-bold">{{ __('issues.fields.severity') }}</label><select id="admin-severity" wire:model="severity" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($severityOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div>
            <div><label for="admin-priority" class="block text-sm font-bold">{{ __('issues.fields.priority') }}</label><select id="admin-priority" wire:model="priority" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($priorityOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div>
            <p class="text-xs leading-5 text-slate-500 sm:col-span-2">{{ __('issues.hints.severity_priority') }}</p><button type="submit" wire:loading.attr="disabled" wire:target="classify" class="min-h-11 rounded-control bg-slate-800 px-4 py-2 font-bold text-white disabled:opacity-50 sm:col-span-2">{{ __('issues.actions.classify') }}</button>
        </form>

        @if ($canAssign)<form wire:submit="assign" class="space-y-3 border-t border-slate-100 pt-4">
            <label for="admin-team" class="block text-sm font-bold">{{ __('issues.fields.support_team') }}</label><select id="admin-team" wire:model="supportTeam" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($teamOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select>
            <label for="admin-assignee" class="block text-sm font-bold">{{ __('issues.fields.assignee') }}</label><select id="admin-assignee" wire:model="assigneeId" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3"><option value="">{{ __('issues.admin.unassigned') }}</option>@foreach ($assigneeOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select>
            <button type="submit" wire:loading.attr="disabled" wire:target="assign" class="min-h-11 rounded-control bg-slate-800 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.actions.assign') }}</button>
        </form>@endif

        @if ($canResolve)<form wire:submit="resolve" class="space-y-3 border-t border-slate-100 pt-4">
            <label for="admin-resolution" class="block text-sm font-bold">{{ __('issues.fields.resolution') }}</label><select id="admin-resolution" wire:model="resolutionType" required class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3"><option value="">{{ __('issues.detail.choose_resolution') }}</option>@foreach ($resolutionOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select>
            <label for="admin-resolution-summary" class="block text-sm font-bold">{{ __('issues.fields.resolution_summary') }}</label><textarea id="admin-resolution-summary" wire:model="resolutionSummary" required rows="4" maxlength="2000" class="w-full rounded-control border border-slate-300 p-3"></textarea>
            <label for="admin-resolution-private" class="block text-sm font-bold">{{ __('issues.fields.private_note') }}</label><textarea id="admin-resolution-private" wire:model="resolutionPrivateNote" rows="3" maxlength="4000" class="w-full rounded-control border border-slate-300 p-3"></textarea>
            <button type="submit" wire:loading.attr="disabled" wire:target="resolve" class="min-h-11 rounded-control bg-emerald-700 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.actions.resolve') }}</button>
        </form>@endif

        <form wire:submit="addInternalNote" class="space-y-3 border-t border-slate-100 pt-4"><label for="admin-internal-note" class="block text-sm font-bold">{{ __('issues.fields.internal_note') }}</label><textarea id="admin-internal-note" wire:model="internalNote" required rows="4" maxlength="6000" class="w-full rounded-control border border-violet-300 p-3"></textarea><button type="submit" wire:loading.attr="disabled" wire:target="addInternalNote" class="min-h-11 rounded-control bg-violet-700 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.actions.add_internal_note') }}</button></form>
        <form wire:submit="merge" class="space-y-3 border-t border-slate-100 pt-4"><label for="admin-merge" class="block text-sm font-bold">{{ __('issues.fields.merge_number') }}</label><input id="admin-merge" wire:model="mergeNumber" type="text" maxlength="44" class="min-h-11 w-full rounded-control border border-slate-300 px-3 font-mono"><button type="submit" wire:confirm="{{ __('issues.confirmations.merge') }}" wire:loading.attr="disabled" wire:target="merge" class="min-h-11 rounded-control bg-amber-700 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.actions.merge') }}</button></form>
        <form wire:submit="redact" class="space-y-3 border-t border-slate-100 pt-4"><label for="admin-redaction" class="block text-sm font-bold">{{ __('issues.detail.redaction_field') }}</label><select id="admin-redaction" wire:model="redactionField" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3"><option value="summary">{{ __('issues.fields.summary') }}</option><option value="expected_behavior">{{ __('issues.fields.expected_behavior') }}</option><option value="actual_behavior">{{ __('issues.fields.actual_behavior') }}</option><option value="reproduction_steps">{{ __('issues.fields.reproduction_steps') }}</option><option value="resolution_summary">{{ __('issues.fields.resolution_summary') }}</option></select><button type="submit" wire:confirm="{{ __('issues.confirmations.redact_field') }}" wire:loading.attr="disabled" wire:target="redact" class="min-h-11 rounded-control bg-rose-700 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.actions.redact') }}</button></form>

        @if ($issue->licensedMediaId)
            <form wire:submit="applySourceAction" class="space-y-3 border-t border-slate-100 pt-4"><label for="admin-source-action" class="block text-sm font-bold">{{ __('issues.admin.source_health') }}</label><select id="admin-source-action" wire:model="sourceAction" class="min-h-11 w-full rounded-control border border-slate-300 bg-white px-3">@foreach ($sourceActionOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select><p class="text-xs leading-5 text-slate-500">{{ __('issues.detail.source_safety') }}</p><button type="submit" wire:confirm="{{ __('issues.confirmations.source_action') }}" wire:loading.attr="disabled" wire:target="applySourceAction" class="min-h-11 rounded-control bg-slate-800 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.admin.source_health') }}</button></form>
        @endif
    </div>
</x-ui.panel>
