<div class="mx-auto max-w-7xl space-y-5">
    <header class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel sm:p-6"><p class="text-xs font-black uppercase tracking-widest text-emerald-700">{{ __('issues.title') }}</p><h1 class="mt-2 text-2xl font-black text-slate-900 sm:text-3xl">{{ __('issues.support_queue') }}</h1><p class="mt-2 max-w-4xl text-sm leading-6 text-slate-600">{{ __('issues.admin.description') }}</p></header>
    @if ($statusMessage)<p role="status" aria-live="polite" class="rounded-control bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ $statusMessage }}</p>@endif
    @if ($actionError)<p role="alert" class="rounded-control bg-rose-50 p-4 text-sm font-bold text-rose-800">{{ $actionError }}</p>@endif
    @if ($schemaReady)<section aria-labelledby="support-counts" class="rounded-panel border border-slate-200 bg-white p-4 shadow-panel"><h2 id="support-counts" class="font-black text-slate-900">{{ __('issues.admin.counts') }}</h2><dl class="mt-3 flex flex-wrap gap-3">@foreach ($counts as $statusCode => $count)<div class="rounded-control bg-slate-50 px-3 py-2"><dt class="text-xs text-slate-500">{{ __('issues.statuses.'.$statusCode) }}</dt><dd class="font-black text-slate-900">{{ $count }}</dd></div>@endforeach</dl></section>@endif

    <section aria-labelledby="support-filters" class="rounded-panel border border-slate-200 bg-white p-4 shadow-panel sm:p-5">
        <div class="flex items-center justify-between gap-3"><h2 id="support-filters" class="font-black text-slate-900">{{ __('issues.admin.filters') }}</h2><button type="button" wire:click="clearFilters" class="min-h-11 rounded-control px-3 text-sm font-bold text-emerald-700">{{ __('issues.actions.clear_filters') }}</button></div>
        <div class="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
            <div class="sm:col-span-2"><label for="support-search" class="block text-sm font-bold">{{ __('issues.fields.search') }}</label><input id="support-search" wire:model.live.debounce.350ms="search" type="search" maxlength="120" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3"></div>
            <x-technical-issues.filter-select id="support-status" property="status" :label="__('issues.fields.status')" :options="$statusOptions" /><x-technical-issues.filter-select id="support-type" property="type" :label="__('issues.fields.issue_type')" :options="$typeOptions" /><x-technical-issues.filter-select id="support-severity" property="severity" :label="__('issues.fields.severity')" :options="$severityOptions" /><x-technical-issues.filter-select id="support-priority" property="priority" :label="__('issues.fields.priority')" :options="$priorityOptions" /><x-technical-issues.filter-select id="support-team" property="team" :label="__('issues.fields.support_team')" :options="$teamOptions" /><x-technical-issues.filter-select id="support-target" property="targetType" :label="__('issues.fields.target')" :options="$targetOptions" /><x-technical-issues.filter-select id="support-source-health" property="sourceHealth" :label="__('issues.diagnostics.source_health')" :options="$sourceHealthOptions" />
            <div><label for="support-assignment" class="block text-sm font-bold">{{ __('issues.fields.assignee') }}</label><select id="support-assignment" wire:model.live="assignment" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 bg-white px-3"><option value="">{{ __('issues.admin.all') }}</option><option value="unassigned">{{ __('issues.admin.unassigned') }}</option><option value="mine">{{ __('issues.admin.assigned_to_me') }}</option></select></div>
            <x-technical-issues.filter-select id="support-sort" property="sort" :label="__('issues.fields.sort')" :options="$sortOptions" :include-all="false" />
        </div>
    </section>

    @if ($schemaReady && count($selectedIssues) > 0)
        <section aria-labelledby="bulk-actions" class="rounded-panel border border-amber-200 bg-amber-50 p-4"><h2 id="bulk-actions" class="font-black text-amber-950">{{ __('issues.admin.bulk_title', ['count' => count($selectedIssues)]) }}</h2><p class="mt-2 text-sm text-amber-900">{{ __('issues.admin.bulk_notice') }}</p><label class="mt-3 flex min-h-11 items-center gap-3 font-bold text-amber-950"><input wire:model="bulkConfirmed" type="checkbox" class="size-5 rounded border-amber-400 text-amber-700">{{ __('issues.admin.bulk_confirm') }}</label><div class="mt-4 grid gap-3 sm:grid-cols-2"><form wire:submit="applyBulkPriority" class="flex flex-wrap items-end gap-2"><div class="min-w-48 flex-1"><label for="bulk-priority" class="block text-sm font-bold">{{ __('issues.fields.priority') }}</label><select id="bulk-priority" wire:model="bulkPriority" class="mt-2 min-h-11 w-full rounded-control border border-amber-300 bg-white px-3">@foreach ($priorityOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div><button type="submit" wire:loading.attr="disabled" class="min-h-11 rounded-control bg-amber-800 px-4 font-bold text-white">{{ __('issues.admin.bulk_priority') }}</button></form><form wire:submit="applyBulkAssignment" class="space-y-2"><div class="grid gap-2 sm:grid-cols-2"><div><label for="bulk-team" class="block text-sm font-bold">{{ __('issues.fields.support_team') }}</label><select id="bulk-team" wire:model="bulkTeam" class="mt-2 min-h-11 w-full rounded-control border border-amber-300 bg-white px-3">@foreach ($teamOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div><div><label for="bulk-assignee" class="block text-sm font-bold">{{ __('issues.fields.assignee') }}</label><select id="bulk-assignee" wire:model="bulkAssigneeId" class="mt-2 min-h-11 w-full rounded-control border border-amber-300 bg-white px-3"><option value="">{{ __('issues.admin.unassigned') }}</option>@foreach ($assigneeOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div></div><button type="submit" wire:loading.attr="disabled" class="min-h-11 rounded-control bg-amber-800 px-4 font-bold text-white">{{ __('issues.admin.bulk_assign') }}</button></form></div></section>
    @endif

    <div wire:loading.delay role="status" aria-live="polite" class="rounded-control bg-sky-50 p-3 text-sm font-bold text-sky-800">{{ __('issues.states.loading') }}</div>
    @if (! $schemaReady)<p class="rounded-control bg-amber-50 p-4 text-sm font-bold text-amber-900">{{ __('issues.states.schema_unavailable') }}</p>@elseif ($issues->isEmpty())<section class="rounded-panel border border-dashed border-slate-300 bg-white p-8 text-center"><h2 class="font-black text-slate-900">{{ __('issues.states.support_empty') }}</h2><button type="button" wire:click="clearFilters" class="mt-4 min-h-11 rounded-control bg-slate-100 px-4 font-bold text-slate-700">{{ __('issues.actions.clear_filters') }}</button></section>@else<div class="grid gap-4 lg:grid-cols-2">@foreach ($issues as $issue)<x-technical-issues.card :issue="$issue" staff selectable :selected="in_array($issue->id, $selectedIssues, true)" />@endforeach</div><div>{{ $issues->links() }}</div>@endif
</div>
