<div class="mx-auto max-w-6xl space-y-5">
    <header class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel sm:p-6">
        <div class="flex min-w-0 flex-wrap items-start justify-between gap-4">
            <div class="min-w-0">
                <div class="flex flex-wrap items-center gap-2 text-xs font-bold"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-emerald-800">{{ $issue->card->typeLabel }}</span><span class="rounded-full bg-slate-100 px-2.5 py-1 text-slate-700">{{ $issue->card->statusLabel }}</span></div>
                <h1 class="mt-3 break-all text-2xl font-black text-slate-900 sm:text-3xl">{{ $issue->card->number }}</h1>
                <p class="mt-2 break-words font-bold text-slate-700">{{ $issue->card->targetLabel }}</p>
                @if ($issue->card->summary)<p class="mt-3 whitespace-pre-wrap break-words text-sm leading-6 text-slate-600">{{ $issue->card->summary }}</p>@endif
            </div>
            @if ($issue->permissions['confirm'] || $issue->permissions['follow'] || $issue->card->hasConfirmed || $issue->card->isFollowing)
                <div class="flex flex-wrap gap-2">
                    @if ($issue->permissions['confirm'] || $issue->card->hasConfirmed)<button type="button" wire:click="setConfirm({{ $issue->card->hasConfirmed ? 'false' : 'true' }})" wire:loading.attr="disabled" wire:target="setConfirm" aria-pressed="{{ $issue->card->hasConfirmed ? 'true' : 'false' }}" class="min-h-11 rounded-control px-4 py-2 text-sm font-bold {{ $issue->card->hasConfirmed ? 'bg-emerald-700 text-white' : 'bg-slate-100 text-slate-700' }}">{{ $issue->card->hasConfirmed ? __('issues.actions.unconfirm') : __('issues.actions.confirm') }}</button>@endif
                    @if ($issue->permissions['follow'] || $issue->card->isFollowing)<button type="button" wire:click="setFollow({{ $issue->card->isFollowing ? 'false' : 'true' }})" wire:loading.attr="disabled" wire:target="setFollow" aria-pressed="{{ $issue->card->isFollowing ? 'true' : 'false' }}" class="min-h-11 rounded-control px-4 py-2 text-sm font-bold {{ $issue->card->isFollowing ? 'bg-sky-700 text-white' : 'bg-slate-100 text-slate-700' }}">{{ $issue->card->isFollowing ? __('issues.actions.unfollow') : __('issues.actions.follow') }}</button>@endif
                </div>
            @endif
        </div>
        <dl class="mt-5 grid gap-3 border-t border-slate-100 pt-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><div><dt class="text-slate-500">{{ __('issues.fields.status') }}</dt><dd class="mt-1 font-bold text-slate-800">{{ $issue->card->statusLabel }}</dd></div><div><dt class="text-slate-500">{{ __('issues.detail.created') }}</dt><dd class="mt-1 font-bold text-slate-800">{{ $issue->card->createdAt }}</dd></div><div><dt class="text-slate-500">{{ __('issues.detail.updated') }}</dt><dd class="mt-1 font-bold text-slate-800">{{ $issue->card->updatedAt }}</dd></div><div><dt class="text-slate-500">{{ $issue->viewerMode === 'staff' ? __('issues.card.affected', ['count' => $issue->card->affectedUserCount]) : __('issues.card.confirmations', ['count' => $issue->card->confirmationCount]) }}</dt><dd class="mt-1 font-bold text-slate-800">{{ $issue->viewerMode === 'staff' ? $issue->card->affectedUserCount : $issue->card->confirmationCount }}</dd></div></dl>
    </header>

    @if (session('technical_issue_status'))<p role="status" aria-live="polite" class="rounded-control bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ session('technical_issue_status') }}</p>@endif
    @if ($statusMessage)<p role="status" aria-live="polite" class="rounded-control bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ $statusMessage }}</p>@endif
    @if ($actionError)<p role="alert" class="rounded-control bg-rose-50 p-4 text-sm font-bold text-rose-800">{{ $actionError }}</p>@endif
    <div wire:loading.delay role="status" aria-live="polite" class="rounded-control bg-sky-50 p-3 text-sm font-bold text-sky-800">{{ __('issues.states.loading') }}</div>

    @if ($issue->mergedIntoNumber)<section class="rounded-panel border border-amber-200 bg-amber-50 p-5"><h2 class="font-black text-amber-950">{{ __('issues.detail.merged_title') }}</h2><p class="mt-2 text-sm text-amber-900">{{ __('issues.detail.merged_notice') }}</p>@if ($issue->mergedIntoUrl)<a href="{{ $issue->mergedIntoUrl }}" class="mt-3 inline-flex min-h-11 flex-wrap items-center gap-2 rounded-control bg-white px-4 py-2 font-bold text-amber-900"><span>{{ $issue->mergedIntoNumber }}</span>@if ($issue->mergedIntoStatusLabel)<span class="text-sm font-semibold text-amber-800">· {{ __('issues.fields.status') }}: {{ $issue->mergedIntoStatusLabel }}</span>@endif</a>@endif</section>@endif

    @if ($issue->viewerMode === 'participant')
        <x-ui.panel :title="__('issues.detail.participant_title')" icon="fa-solid fa-shield-halved"><p class="text-sm leading-6 text-slate-600">{{ __('issues.detail.participant_notice') }}</p>@if ($issue->resolutionSummary)<div class="mt-4 rounded-control bg-emerald-50 p-4"><strong class="text-emerald-900">{{ $issue->resolutionTypeLabel }}</strong><p class="mt-2 whitespace-pre-wrap break-words text-sm text-emerald-900">{{ $issue->resolutionSummary }}</p></div>@endif</x-ui.panel>
        @if ($issue->permissions['verify'] || $issue->permissions['reopen'])<x-technical-issues.resolution-verification :can-verify="$issue->permissions['verify']" />@endif
    @else
        <div class="grid gap-5 lg:grid-cols-[minmax(0,1.3fr)_minmax(18rem,.7fr)]">
            <div class="space-y-5">
                <x-ui.panel :title="__('issues.detail.report_title')" icon="fa-solid fa-circle-info">
                    <dl class="space-y-4 text-sm">@if ($issue->expectedBehavior)<div><dt class="font-black text-slate-800">{{ __('issues.fields.expected_behavior') }}</dt><dd class="mt-1 whitespace-pre-wrap break-words leading-6 text-slate-600">{{ $issue->expectedBehavior }}</dd></div>@endif @if ($issue->actualBehavior)<div><dt class="font-black text-slate-800">{{ __('issues.fields.actual_behavior') }}</dt><dd class="mt-1 whitespace-pre-wrap break-words leading-6 text-slate-600">{{ $issue->actualBehavior }}</dd></div>@endif @if ($issue->reproductionSteps)<div><dt class="font-black text-slate-800">{{ __('issues.fields.reproduction_steps') }}</dt><dd class="mt-1 whitespace-pre-wrap break-words leading-6 text-slate-600">{{ $issue->reproductionSteps }}</dd></div>@endif</dl>
                    @if ($issue->playbackTimestamp || $issue->audioLanguage || $issue->subtitleLanguage || $issue->qualityCode || $issue->publicErrorCode)<dl class="mt-5 grid gap-3 border-t border-slate-100 pt-4 text-sm sm:grid-cols-2">@if ($issue->playbackTimestamp)<div><dt class="text-slate-500">{{ __('issues.fields.playback_timestamp') }}</dt><dd class="font-bold">{{ $issue->playbackTimestamp }}</dd></div>@endif @if ($issue->audioLanguage)<div><dt class="text-slate-500">{{ __('issues.fields.audio_language') }}</dt><dd class="font-bold">{{ $issue->audioLanguage }}</dd></div>@endif @if ($issue->subtitleLanguage)<div><dt class="text-slate-500">{{ __('issues.fields.subtitle_language') }}</dt><dd class="font-bold">{{ $issue->subtitleLanguage }}</dd></div>@endif @if ($issue->qualityCode)<div><dt class="text-slate-500">{{ __('issues.fields.quality') }}</dt><dd class="font-bold">{{ $issue->qualityCode }}</dd></div>@endif @if ($issue->publicErrorCode)<div><dt class="text-slate-500">{{ __('issues.fields.error_code') }}</dt><dd class="break-all font-mono font-bold">{{ $issue->publicErrorCode }}</dd></div>@endif</dl>@endif
                </x-ui.panel>

                <x-ui.panel :title="__('issues.fields.screenshots')" icon="fa-solid fa-image">@if (count($issue->attachments) === 0)<p class="text-sm text-slate-500">{{ __('issues.states.attachment_empty') }}</p>@else<div class="grid gap-4 sm:grid-cols-2">@foreach ($issue->attachments as $attachment)<figure class="min-w-0 overflow-hidden rounded-control border border-slate-200"><a href="{{ $attachment['url'] }}" target="_blank" rel="noopener noreferrer"><img src="{{ $attachment['url'] }}" alt="{{ $attachment['name'] }}" loading="lazy" class="aspect-video w-full bg-slate-100 object-contain"></a><figcaption class="break-words p-3 text-xs text-slate-600">{{ $attachment['name'] }} · {{ $attachment['width'] }} × {{ $attachment['height'] }}</figcaption></figure>@endforeach</div>@endif</x-ui.panel>

                @island(name: 'technical-issue-messages-pagination', always: true, with: $this->paginationIslandPage)
                <x-ui.pagination-region name="technical-issue-messages-results">
                <x-ui.panel :title="__('issues.detail.messages_title')" icon="fa-solid fa-comments">
                    @if (count($issue->messages) === 0)<p class="text-sm text-slate-500">{{ __('issues.detail.no_messages') }}</p>@else<div class="space-y-3">@foreach ($issue->messages as $message)<article wire:key="technical-message-{{ $message['id'] }}" class="rounded-control p-4 {{ $message['internal'] ? 'border border-violet-200 bg-violet-50' : 'bg-slate-50' }}"><div class="flex flex-wrap justify-between gap-2 text-xs font-bold text-slate-500"><span>{{ $message['internal'] ? __('issues.messages.internal') : $message['author'] }}</span><time>{{ $message['created_at'] }}</time></div><p class="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{{ $message['body'] }}</p>@if (count($message['attachments']) > 0)<ul class="mt-3 space-y-2">@foreach ($message['attachments'] as $attachment)<li><a href="{{ $attachment['url'] }}" target="_blank" rel="noopener noreferrer" class="inline-flex min-h-11 max-w-full items-center gap-2 break-words rounded-control bg-white px-3 py-2 text-sm font-bold text-emerald-700"><x-ui.icon name="fa-solid fa-paperclip" />{{ $attachment['name'] }}</a></li>@endforeach</ul>@endif @if ($issue->permissions['manage'])<button type="button" wire:click="redactMessage('{{ $message['id'] }}')" wire:confirm="{{ __('issues.confirmations.redact_message') }}" wire:loading.attr="disabled" wire:target="redactMessage('{{ $message['id'] }}')" class="mt-3 min-h-11 rounded-control bg-white px-3 text-xs font-bold text-rose-700 disabled:opacity-50">{{ __('issues.actions.redact') }}</button>@endif</article>@endforeach</div>@if ($issue->messagePages?->hasPages())<nav class="mt-4" aria-label="{{ __('issues.detail.messages_title') }}">{{ $issue->messagePages->links(data: ['region' => 'technical-issue-messages-results']) }}</nav>@endif @endif
                    @if ($issue->permissions['reply'])<form wire:submit="sendMessage" class="mt-5 space-y-3 border-t border-slate-100 pt-4"><label for="technical-message" class="block text-sm font-bold text-slate-700">{{ __('issues.fields.message') }}</label><textarea id="technical-message" wire:model="messageBody" rows="5" maxlength="6000" required class="w-full rounded-control border border-slate-300 p-3"></textarea><input wire:model="messageScreenshots" type="file" aria-label="{{ __('issues.fields.screenshots') }}" accept="image/jpeg,image/png,image/webp" multiple class="block w-full text-sm text-slate-600 file:mr-3 file:min-h-11 file:rounded-control file:border-0 file:bg-slate-100 file:px-3 file:py-2.5 file:font-bold file:text-slate-700">@if (count($messageScreenshots) > 0)<ul class="space-y-2">@foreach ($messageScreenshots as $index => $screenshot)<li wire:key="reply-screenshot-{{ $index }}-{{ $screenshot->getFilename() }}" class="flex items-center gap-3 rounded-control border p-2 text-sm"><img src="{{ $screenshot->temporaryUrl() }}" alt="{{ __('issues.attachments.preview_alt', ['number' => $index + 1]) }}" class="size-14 shrink-0 rounded-control bg-slate-100 object-cover"><span class="min-w-0 flex-1 break-words">{{ __('issues.attachments.screenshot_name', ['number' => $index + 1]) }}</span><button type="button" wire:click="removeMessageScreenshot({{ $index }})" class="min-h-11 shrink-0 px-3 font-bold">{{ __('issues.actions.remove_attachment') }}</button></li>@endforeach</ul>@endif<button type="submit" wire:loading.attr="disabled" wire:target="sendMessage,messageScreenshots" class="min-h-11 rounded-control bg-emerald-700 px-4 py-2 font-bold text-white">{{ __('issues.actions.send_reply') }}</button></form>@endif
                </x-ui.panel>
                </x-ui.pagination-region>
                @endisland

                <x-ui.panel :title="__('issues.timeline.title')" icon="fa-solid fa-clock-rotate-left">@if (count($issue->history) === 0)<p class="text-sm text-slate-500">{{ __('issues.states.history_empty') }}</p>@else<ol class="space-y-4">@foreach ($issue->history as $entry)<li wire:key="technical-history-{{ $entry['id'] }}" class="border-l-2 border-emerald-200 pl-4"><div class="flex flex-wrap justify-between gap-2"><strong class="text-sm text-slate-800">{{ $entry['label'] }}</strong><time class="text-xs text-slate-500">{{ $entry['created_at'] }}</time></div>@if ($entry['reason'])<p class="mt-1 whitespace-pre-wrap break-words text-sm text-slate-600">{{ $entry['reason'] }}</p>@endif @if ($entry['private_note'])<p class="mt-2 rounded-control bg-violet-50 p-2 text-xs text-violet-900"><strong>{{ __('issues.fields.private_note') }}:</strong> {{ $entry['private_note'] }}</p>@endif</li>@endforeach</ol>@endif</x-ui.panel>
            </div>

            <aside class="space-y-5">
                @if ($issue->resolutionSummary)<x-ui.panel :title="__('issues.fields.resolution')" icon="fa-solid fa-circle-check"><p class="font-bold text-emerald-800">{{ $issue->resolutionTypeLabel }}</p><p class="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-600">{{ $issue->resolutionSummary }}</p></x-ui.panel>@endif
                @if ($issue->diagnostics)<x-ui.panel :title="__('issues.diagnostics.title')" icon="fa-solid fa-laptop"><dl class="space-y-3 text-sm">@foreach ($issue->diagnostics as $key => $value)<div><dt class="text-slate-500">{{ __('issues.diagnostics.'.$key) }}</dt><dd class="mt-1 break-words font-bold text-slate-800">@if (is_bool($value)){{ $value ? __('issues.diagnostics.yes') : __('issues.diagnostics.no') }}@else{{ $value }}@endif</dd></div>@endforeach</dl></x-ui.panel>@endif
                @if ($issue->permissions['edit'])<x-technical-issues.requester-edit />@endif
                @if ($issue->permissions['verify'] || $issue->permissions['reopen'])<x-technical-issues.resolution-verification :can-verify="$issue->permissions['verify']" />@endif
                @if ($issue->permissions['withdraw'])<section class="rounded-panel border border-rose-200 bg-white p-5 shadow-panel"><h2 class="font-black text-slate-900">{{ __('issues.detail.withdraw_title') }}</h2><p class="mt-2 text-sm text-slate-600">{{ __('issues.detail.withdraw_notice') }}</p><button type="button" wire:click="withdraw" wire:confirm="{{ __('issues.confirmations.withdraw') }}" wire:loading.attr="disabled" wire:target="withdraw" class="mt-3 min-h-11 rounded-control bg-rose-700 px-4 py-2 font-bold text-white disabled:opacity-50">{{ __('issues.actions.withdraw') }}</button></section>@endif
                @if ($issue->permissions['manage'])<x-technical-issues.staff-controls :issue="$issue" :status-options="$statusOptions" :severity-options="$severityOptions" :priority-options="$priorityOptions" :resolution-options="$resolutionOptions" :team-options="$teamOptions" :assignee-options="$assigneeOptions" :rejection-options="$rejectionOptions" :reroute-options="$rerouteOptions" :source-action-options="$sourceActionOptions" :can-resolve="$canResolve" :can-assign="$canAssign" />@endif
            </aside>
        </div>
    @endif
</div>
