<section aria-labelledby="technical-notification-title" class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel">
    @island(name: 'technical-issue-notifications-pagination', always: true, with: $this->paginationIslandPage)
    <x-ui.pagination-region name="technical-issue-notifications-results">
    <div class="flex flex-wrap items-start justify-between gap-3"><div><h2 id="technical-notification-title" class="text-lg font-black text-slate-900">{{ __('issues.notifications.title') }}</h2><p class="mt-1 text-sm text-slate-600">{{ __('issues.notifications.description') }}</p></div><button type="button" wire:click="markAllRead" wire:loading.attr="disabled" class="min-h-11 rounded-control bg-slate-100 px-3 text-sm font-bold text-slate-700">{{ __('issues.actions.mark_all_read') }}</button></div>
    @if ($statusMessage)<p role="status" class="mt-3 rounded-control bg-emerald-50 p-3 text-sm font-bold text-emerald-800">{{ $statusMessage }}</p>@endif
    @if ($actionError)<p role="alert" class="mt-3 rounded-control bg-rose-50 p-3 text-sm font-bold text-rose-800">{{ $actionError }}</p>@endif
    @if (! $schemaReady)<p class="mt-4 rounded-control bg-amber-50 p-3 text-sm font-bold text-amber-900">{{ __('issues.states.schema_unavailable') }}</p>@else
        <form wire:submit="savePreferences" class="mt-4 grid gap-2 border-y border-slate-100 py-4 sm:grid-cols-2">@foreach ([['requesterUpdates', 'requester_updates'], ['confirmerUpdates', 'confirmer_updates'], ['followerUpdates', 'follower_updates'], ['supportReplies', 'support_replies']] as $preference)<label class="flex min-h-11 items-center gap-3 rounded-control bg-slate-50 px-3 text-sm font-bold text-slate-700"><input wire:model="{{ $preference[0] }}" type="checkbox" class="size-5 rounded border-slate-300 text-emerald-700">{{ __('issues.notifications.'.$preference[1]) }}</label>@endforeach<button type="submit" wire:loading.attr="disabled" class="mt-2 min-h-11 rounded-control bg-slate-800 px-4 font-bold text-white sm:col-span-2">{{ __('issues.actions.save') }}</button></form>
        @if ($notifications->isEmpty())<p class="mt-4 text-sm text-slate-500">{{ __('issues.notifications.empty') }}</p>@else<ul class="mt-4 space-y-3">@foreach ($notifications as $notification)<li wire:key="issue-notification-{{ $notification->id }}" class="rounded-control border p-3 {{ $notification->isRead ? 'border-slate-200' : 'border-emerald-300 bg-emerald-50' }}"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="font-bold text-slate-900">{{ $notification->label }}</p>@if ($notification->detail)<p class="mt-1 text-sm text-slate-600">{{ $notification->detail }}</p>@endif<time datetime="{{ $notification->createdAtIso }}" class="mt-1 block text-xs text-slate-500">{{ $notification->createdAtLabel }}</time></div><div class="flex flex-wrap gap-2">@if ($notification->url)<a href="{{ $notification->url }}" class="inline-flex min-h-11 items-center rounded-control bg-white px-3 text-sm font-bold text-emerald-700">{{ __('issues.actions.open_ticket') }}</a>@endif @if (! $notification->isRead)<button type="button" wire:click="markRead('{{ $notification->id }}')" wire:loading.attr="disabled" wire:target="markRead('{{ $notification->id }}')" class="min-h-11 rounded-control bg-slate-100 px-3 text-sm font-bold text-slate-700 disabled:opacity-50">{{ __('issues.actions.mark_read') }}</button>@endif</div></div></li>@endforeach</ul><div class="mt-4">{{ $notifications->links(data: ['region' => 'technical-issue-notifications-results']) }}</div>@endif
    @endif
    </x-ui.pagination-region>
    @endisland
</section>
