<?php

return [
    'version' => 'task18-v6',
    'section_limit' => 12,
    'page_size' => 24,
    'candidate_limit' => 180,
    'history_title_limit' => 120,
    'meaningful_progress_percent' => 10,
    'meaningful_progress_seconds' => 180,
    'repeat_suppression' => [
        'max_ids' => 96,
        'days' => 7,
    ],
    'diversity' => [
        'franchise_limit' => 2,
        'primary_genre_limit' => 5,
        'leading_actor_limit' => 4,
    ],
    'soft_demotions' => [
        'watchlist' => 40,
        'planned' => 30,
        'watching' => 80,
        'completed' => 100,
        'dropped' => 120,
    ],
    'availability_boosts' => [
        'quality' => 12,
        'variant' => 12,
        'subtitles' => 6,
    ],
    'top_rated' => [
        'default_source' => 'kinopoisk',
        'minimum_votes' => [
            'portal' => 5,
            'kinopoisk' => 1_000,
            'imdb' => 1_000,
        ],
    ],
    'trending' => [
        'default_period' => 'week',
        'maximum_period_days' => 30,
    ],
    'content_updates' => [
        'event_window_multiplier' => 64,
        'minimum_event_window' => 10_000,
        'maximum_event_window' => 20_000,
    ],
    'random' => [
        'maximum_probes' => 12,
        'probe_size' => 8,
    ],
    'personalized' => [
        'history_weight' => 120,
        'completed_weight' => 160,
        'watchlist_weight' => 140,
        'status_weight' => 135,
        'collection_weight' => 110,
        'personal_tag_weight' => 100,
        'rating_weight' => 130,
        'public_fallback_limit' => 24,
    ],
    'personalized_v2' => [
        'enabled' => filter_var(env('RECOMMENDATIONS_PERSONALIZED_V2_ENABLED', false), FILTER_VALIDATE_BOOL),
        'rollout_percent' => (int) env('RECOMMENDATIONS_PERSONALIZED_V2_PERCENT', 0),
        'rollout_seed' => 'personalized-v2',
        'history_limit' => 120,
        'source_confidence_cap' => 320,
        'profile_high_threshold' => 600,
        'recency_half_life_days' => 180,
        'legacy_recency_factor' => 0.5,
        'negative_minimum_sources' => 3,
        'negative_feature_cap' => 120,
        'negative_total_cap' => 240,
        'exploration_ratio' => 0.15,
        'exploration_relevance_floor' => 0.45,
    ],
    'similarity_v6' => [
        'algorithm_version' => 'v6',
        'feature_version' => 'tokens-v2',
        'shadow_enabled' => true,
        'allow_activation_without_golden' => false,
        'min_relevance_score' => 600,
        'max_per_title' => 12,
        'candidate_limit' => 240,
        'dirty_title_limit' => 2_000,
        'scoped_source_limit' => 2_000,
        'scoped_neighbours_per_title' => 240,
        'build_history_limit' => 5,
        'minimum_judgment_coverage' => 0.8,
        'provider_relation_score' => 650,
        'editorial_collection_signal_weight' => 280,
        'collection_signal_score_cap' => 220,
        'collection_signal_multiplier' => 0.8,
        'collection_signal_min_specificity' => 0.25,
        'collection_signal_max_keys' => 32,
        'collection_signal_max_shared' => 3,
        'weights' => [
            'genre' => 160,
            'tag' => 240,
            'director' => 300,
            'actor' => 160,
            'network' => 220,
            'studio' => 220,
            'translation' => 40,
            'status' => 25,
            'country' => 70,
            'age_rating' => 15,
            'theme' => 240,
        ],
        'quality' => [
            'media' => 80,
            'rating' => 40,
            'reviews' => 20,
        ],
    ],
];
