<?php

return [
    'admin_emails' => array_values(array_filter(array_map(
        static fn (string $email): string => mb_strtolower(trim($email)),
        explode(',', (string) env('SEASONVAR_IMPORT_ADMIN_EMAILS', '')),
    ))),
    'base_url' => env('SEASONVAR_BASE_URL', 'https://seasonvar.ru'),
    'sitemap_url' => env('SEASONVAR_SITEMAP_URL', 'https://seasonvar.ru/sitemap_index.xml'),
    'sitemap_storage_directory' => 'seasonvar/sitemaps',
    'crawl_delay_seconds' => (int) env('SEASONVAR_CRAWL_DELAY', 3),
    'import' => [
        'chunk_size' => (int) env('SEASONVAR_IMPORT_CHUNK_SIZE', 100),
        'max_linked_serial_urls' => (int) env('SEASONVAR_IMPORT_MAX_LINKED_SERIAL_URLS', 100),
        'linked_serial_defer_minutes' => (int) env('SEASONVAR_IMPORT_LINKED_SERIAL_DEFER_MINUTES', 5),
        'sleep_seconds' => (int) env('SEASONVAR_IMPORT_SLEEP_SECONDS', 60),
        'refresh_after_hours' => (int) env('SEASONVAR_IMPORT_REFRESH_AFTER_HOURS', 24),
        'missing_data_retry_hours' => (int) env('SEASONVAR_IMPORT_MISSING_DATA_RETRY_HOURS', 24),
        'lock_seconds' => (int) env('SEASONVAR_IMPORT_LOCK_SECONDS', 604800),
        'stale_after_minutes' => (int) env('SEASONVAR_IMPORT_STALE_AFTER_MINUTES', 15),
        'transaction_attempts' => (int) env('SEASONVAR_IMPORT_TRANSACTION_ATTEMPTS', 5),
        'transaction_retry_delay_ms' => (int) env('SEASONVAR_IMPORT_TRANSACTION_RETRY_DELAY_MS', 250),
        'storage_maintenance_enabled' => filter_var(env('SEASONVAR_IMPORT_STORAGE_MAINTENANCE_ENABLED', true), FILTER_VALIDATE_BOOL),
        'event_retention_days' => (int) env('SEASONVAR_IMPORT_EVENT_RETENTION_DAYS', 7),
        'snapshot_retention_days' => (int) env('SEASONVAR_IMPORT_SNAPSHOT_RETENTION_DAYS', 14),
        'prepared_retention_days' => (int) env('SEASONVAR_IMPORT_PREPARED_RETENTION_DAYS', 7),
        'maintenance_chunk_size' => (int) env('SEASONVAR_IMPORT_MAINTENANCE_CHUNK_SIZE', 500),
    ],
    'page_types' => [
        'serial' => [
            'enabled' => filter_var(env('SEASONVAR_PAGE_SERIAL_ENABLED', true), FILTER_VALIDATE_BOOL),
            'automatic' => filter_var(env('SEASONVAR_PAGE_SERIAL_AUTOMATIC', true), FILTER_VALIDATE_BOOL),
            'publication_authorized' => filter_var(env('SEASONVAR_PAGE_SERIAL_PUBLICATION_AUTHORIZED', true), FILTER_VALIDATE_BOOL),
            'refresh_after_hours' => (int) env('SEASONVAR_PAGE_SERIAL_REFRESH_HOURS', 24),
            'chunk_size' => (int) env('SEASONVAR_PAGE_SERIAL_CHUNK_SIZE', 100),
        ],
        'actor' => [
            'enabled' => filter_var(env('SEASONVAR_PAGE_ACTOR_ENABLED', false), FILTER_VALIDATE_BOOL),
            'automatic' => filter_var(env('SEASONVAR_PAGE_ACTOR_AUTOMATIC', false), FILTER_VALIDATE_BOOL),
            'publication_authorized' => filter_var(env('SEASONVAR_PAGE_ACTOR_PUBLICATION_AUTHORIZED', false), FILTER_VALIDATE_BOOL),
            'refresh_after_hours' => (int) env('SEASONVAR_PAGE_ACTOR_REFRESH_HOURS', 168),
            'chunk_size' => (int) env('SEASONVAR_PAGE_ACTOR_CHUNK_SIZE', 20),
        ],
        'genre' => [
            'enabled' => filter_var(env('SEASONVAR_PAGE_GENRE_ENABLED', false), FILTER_VALIDATE_BOOL),
            'automatic' => filter_var(env('SEASONVAR_PAGE_GENRE_AUTOMATIC', false), FILTER_VALIDATE_BOOL),
            'publication_authorized' => filter_var(env('SEASONVAR_PAGE_GENRE_PUBLICATION_AUTHORIZED', false), FILTER_VALIDATE_BOOL),
            'refresh_after_hours' => (int) env('SEASONVAR_PAGE_GENRE_REFRESH_HOURS', 168),
            'chunk_size' => (int) env('SEASONVAR_PAGE_GENRE_CHUNK_SIZE', 20),
        ],
        'country' => [
            'enabled' => filter_var(env('SEASONVAR_PAGE_COUNTRY_ENABLED', false), FILTER_VALIDATE_BOOL),
            'automatic' => filter_var(env('SEASONVAR_PAGE_COUNTRY_AUTOMATIC', false), FILTER_VALIDATE_BOOL),
            'publication_authorized' => filter_var(env('SEASONVAR_PAGE_COUNTRY_PUBLICATION_AUTHORIZED', false), FILTER_VALIDATE_BOOL),
            'refresh_after_hours' => (int) env('SEASONVAR_PAGE_COUNTRY_REFRESH_HOURS', 168),
            'chunk_size' => (int) env('SEASONVAR_PAGE_COUNTRY_CHUNK_SIZE', 20),
        ],
        'tag' => [
            'enabled' => filter_var(env('SEASONVAR_PAGE_TAG_ENABLED', false), FILTER_VALIDATE_BOOL),
            'automatic' => filter_var(env('SEASONVAR_PAGE_TAG_AUTOMATIC', false), FILTER_VALIDATE_BOOL),
            'publication_authorized' => filter_var(env('SEASONVAR_PAGE_TAG_PUBLICATION_AUTHORIZED', false), FILTER_VALIDATE_BOOL),
            'refresh_after_hours' => (int) env('SEASONVAR_PAGE_TAG_REFRESH_HOURS', 168),
            'chunk_size' => (int) env('SEASONVAR_PAGE_TAG_CHUNK_SIZE', 20),
        ],
        'rss' => [
            'enabled' => filter_var(env('SEASONVAR_PAGE_RSS_ENABLED', true), FILTER_VALIDATE_BOOL),
            'automatic' => filter_var(env('SEASONVAR_PAGE_RSS_AUTOMATIC', true), FILTER_VALIDATE_BOOL),
            'publication_authorized' => false,
            'refresh_after_hours' => (int) env('SEASONVAR_PAGE_RSS_REFRESH_HOURS', 1),
            'chunk_size' => (int) env('SEASONVAR_PAGE_RSS_CHUNK_SIZE', 5),
        ],
    ],
    'queue' => [
        'connection' => env('SEASONVAR_QUEUE_CONNECTION', 'redis'),
        'queue' => env('SEASONVAR_QUEUE_NAME', 'seasonvar-import'),
        'lock_store' => env('SEASONVAR_QUEUE_LOCK_STORE', 'redis-locks'),
        'claim_seconds' => (int) env('SEASONVAR_QUEUE_CLAIM_SECONDS', 86400),
        'worker_timeout' => (int) env('SEASONVAR_QUEUE_WORKER_TIMEOUT', 900),
        'retry_window_seconds' => (int) env('SEASONVAR_QUEUE_RETRY_WINDOW_SECONDS', 21600),
        'finalizer_delay_seconds' => (int) env('SEASONVAR_QUEUE_FINALIZER_DELAY_SECONDS', 60),
        'busy_threshold' => (int) env('SEASONVAR_QUEUE_BUSY_THRESHOLD', 5000),
        'busy_log_seconds' => (int) env('SEASONVAR_QUEUE_BUSY_LOG_SECONDS', 3600),
        'stale_after_minutes' => (int) env('SEASONVAR_QUEUE_STALE_AFTER_MINUTES', 120),
    ],
    'title_refresh' => [
        'fresh_minutes' => (int) env('SEASONVAR_TITLE_REFRESH_FRESH_MINUTES', 15),
        'queue' => env('SEASONVAR_TITLE_REFRESH_QUEUE', 'seasonvar-title-refresh'),
        'finalizer_delay_seconds' => (int) env('SEASONVAR_TITLE_REFRESH_FINALIZER_DELAY_SECONDS', 5),
        'state_ttl_seconds' => (int) env('SEASONVAR_TITLE_REFRESH_STATE_TTL_SECONDS', 86400),
        'active_seconds' => (int) env('SEASONVAR_TITLE_REFRESH_ACTIVE_SECONDS', 21900),
        'dispatch_lock_seconds' => (int) env('SEASONVAR_TITLE_REFRESH_DISPATCH_LOCK_SECONDS', 10),
    ],
    'media_check' => [
        'enabled' => filter_var(env('SEASONVAR_MEDIA_CHECK_ENABLED', true), FILTER_VALIDATE_BOOL),
        'retries' => (int) env('SEASONVAR_MEDIA_CHECK_RETRIES', 3),
        'timeout_seconds' => (int) env('SEASONVAR_MEDIA_CHECK_TIMEOUT', 10),
        'connect_timeout_seconds' => (int) env('SEASONVAR_MEDIA_CHECK_CONNECT_TIMEOUT', 5),
        'max_response_bytes' => (int) env('SEASONVAR_MEDIA_CHECK_MAX_RESPONSE_BYTES', 65536),
        'chunk_size' => (int) env('SEASONVAR_MEDIA_CHECK_CHUNK_SIZE', 25),
        'max_per_cycle' => (int) env('SEASONVAR_MEDIA_CHECK_MAX_PER_CYCLE', 20),
        'refresh_after_hours' => (int) env('SEASONVAR_MEDIA_CHECK_REFRESH_AFTER_HOURS', 168),
        'unavailable_after_failures' => (int) env('SEASONVAR_MEDIA_CHECK_FAILURE_THRESHOLD', 3),
        'retry_base_minutes' => (int) env('SEASONVAR_MEDIA_CHECK_RETRY_BASE_MINUTES', 15),
        'retry_max_minutes' => (int) env('SEASONVAR_MEDIA_CHECK_RETRY_MAX_MINUTES', 1440),
        'permanent_retry_minutes' => (int) env('SEASONVAR_MEDIA_CHECK_PERMANENT_RETRY_MINUTES', 360),
    ],
    'media_metadata' => [
        'chunk_size' => (int) env('SEASONVAR_MEDIA_METADATA_CHUNK_SIZE', 100),
    ],
    'media_identity' => [
        'chunk_size' => (int) env('SEASONVAR_MEDIA_SOURCE_KEY_CHUNK_SIZE', 250),
    ],
    'metadata_backfill' => [
        'page_chunk_size' => (int) env('SEASONVAR_METADATA_BACKFILL_PAGE_CHUNK_SIZE', 50),
        'page_limit' => (int) env('SEASONVAR_METADATA_BACKFILL_PAGE_LIMIT', 200),
        'title_chunk_size' => (int) env('SEASONVAR_METADATA_BACKFILL_TITLE_CHUNK_SIZE', 50),
        'title_limit' => (int) env('SEASONVAR_METADATA_BACKFILL_TITLE_LIMIT', 200),
    ],
    'recommendations' => [
        'chunk_size' => (int) env('SEASONVAR_RECOMMENDATION_CHUNK_SIZE', 100),
        'min_score' => (int) env('SEASONVAR_RECOMMENDATION_MIN_SCORE', 600),
        'max_per_title' => (int) env('SEASONVAR_RECOMMENDATION_MAX_PER_TITLE', 12),
        'candidate_limit' => (int) env('SEASONVAR_RECOMMENDATION_CANDIDATE_LIMIT', 120),
        'candidate_scan_per_feature' => (int) env('SEASONVAR_RECOMMENDATION_CANDIDATE_SCAN_PER_FEATURE', 60),
    ],
];
