<?php

declare(strict_types=1);

namespace App\Services\Admin;

use App\Enums\AdminPermission;
use App\Enums\AdminRoleCode;

final class AdminAccessRegistry
{
    /** @return list<AdminPermission> */
    public function permissionsFor(AdminRoleCode $role): array
    {
        $permissions = match ($role) {
            AdminRoleCode::Superadministrator => [
                AdminPermission::DashboardView,
                AdminPermission::RolesView,
                AdminPermission::RolesManage,
                AdminPermission::AdministratorsView,
                AdminPermission::AdministratorsManage,
                AdminPermission::UsersView,
                AdminPermission::UsersRestrict,
                AdminPermission::UsersExport,
                AdminPermission::UsersDelete,
                AdminPermission::ContentView,
                AdminPermission::ContentCreate,
                AdminPermission::ContentManage,
                AdminPermission::ContentPublish,
                AdminPermission::ContentDelete,
                AdminPermission::SourcesView,
                AdminPermission::SourcesManage,
                AdminPermission::SourcesDisable,
                AdminPermission::TranslationsManage,
                AdminPermission::SubtitlesManage,
                AdminPermission::CollectionsModerate,
                AdminPermission::CommentsModerate,
                AdminPermission::ReviewsModerate,
                AdminPermission::ProfilesModerate,
                AdminPermission::RequestsModerate,
                AdminPermission::TicketsSupport,
                AdminPermission::TicketInternalNotes,
                AdminPermission::TicketAttachments,
                AdminPermission::HelpManage,
                AdminPermission::CalendarManage,
                AdminPermission::RecommendationsManage,
                AdminPermission::PremiumView,
                AdminPermission::PremiumGrant,
                AdminPermission::PremiumPromotions,
                AdminPermission::BillingView,
                AdminPermission::AdvertisersView,
                AdminPermission::AdvertisersManage,
                AdminPermission::RightsCasesView,
                AdminPermission::NotificationsManage,
                AdminPermission::ImportsExecute,
                AdminPermission::CacheView,
                AdminPermission::CacheInvalidate,
                AdminPermission::SearchView,
                AdminPermission::SearchReindex,
                AdminPermission::SeoManage,
                AdminPermission::RedirectsManage,
                AdminPermission::SettingsView,
                AdminPermission::SettingsManage,
                AdminPermission::AuditView,
                AdminPermission::AuditExport,
                AdminPermission::OperationsView,
                AdminPermission::OperationsExecute,
            ],
            AdminRoleCode::PortalAdministrator => [
                AdminPermission::DashboardView,
                AdminPermission::AdministratorsView,
                AdminPermission::UsersView,
                AdminPermission::ContentView,
                AdminPermission::ContentManage,
                AdminPermission::CollectionsModerate,
                AdminPermission::CommentsModerate,
                AdminPermission::ReviewsModerate,
                AdminPermission::ProfilesModerate,
                AdminPermission::RequestsModerate,
                AdminPermission::TicketsSupport,
                AdminPermission::HelpManage,
                AdminPermission::CalendarManage,
                AdminPermission::PremiumView,
                AdminPermission::ImportsExecute,
                AdminPermission::AuditView,
                AdminPermission::OperationsView,
            ],
            AdminRoleCode::ContentManager => [
                AdminPermission::DashboardView,
                AdminPermission::ContentView,
                AdminPermission::ContentCreate,
                AdminPermission::ContentManage,
                AdminPermission::ContentPublish,
                AdminPermission::ContentDelete,
                AdminPermission::SourcesView,
                AdminPermission::SourcesManage,
                AdminPermission::SourcesDisable,
                AdminPermission::TranslationsManage,
                AdminPermission::SubtitlesManage,
                AdminPermission::CalendarManage,
                AdminPermission::RecommendationsManage,
                AdminPermission::SeoManage,
            ],
            AdminRoleCode::ContentEditor => [
                AdminPermission::DashboardView,
                AdminPermission::ContentView,
                AdminPermission::ContentCreate,
                AdminPermission::ContentManage,
                AdminPermission::SourcesView,
                AdminPermission::TranslationsManage,
                AdminPermission::SubtitlesManage,
            ],
            AdminRoleCode::Translator => [
                AdminPermission::DashboardView,
                AdminPermission::ContentView,
                AdminPermission::TranslationsManage,
                AdminPermission::SubtitlesManage,
                AdminPermission::HelpManage,
            ],
            AdminRoleCode::MediaManager => [
                AdminPermission::DashboardView,
                AdminPermission::ContentView,
                AdminPermission::SourcesView,
                AdminPermission::SourcesManage,
                AdminPermission::SourcesDisable,
                AdminPermission::SubtitlesManage,
            ],
            AdminRoleCode::Moderator => [
                AdminPermission::DashboardView,
                AdminPermission::UsersView,
                AdminPermission::UsersRestrict,
                AdminPermission::ContentView,
                AdminPermission::CollectionsModerate,
                AdminPermission::CommentsModerate,
                AdminPermission::ReviewsModerate,
                AdminPermission::ProfilesModerate,
                AdminPermission::RequestsModerate,
            ],
            AdminRoleCode::SupportAgent => [
                AdminPermission::DashboardView,
                AdminPermission::UsersView,
                AdminPermission::TicketsSupport,
            ],
            AdminRoleCode::SeniorSupportAgent => [
                AdminPermission::DashboardView,
                AdminPermission::UsersView,
                AdminPermission::UsersRestrict,
                AdminPermission::TicketsSupport,
                AdminPermission::TicketInternalNotes,
                AdminPermission::TicketAttachments,
                AdminPermission::RequestsModerate,
            ],
            AdminRoleCode::PremiumManager => [
                AdminPermission::DashboardView,
                AdminPermission::UsersView,
                AdminPermission::PremiumView,
                AdminPermission::PremiumGrant,
                AdminPermission::PremiumPromotions,
            ],
            AdminRoleCode::BillingManager => [
                AdminPermission::DashboardView,
                AdminPermission::UsersView,
                AdminPermission::PremiumView,
                AdminPermission::BillingView,
                AdminPermission::BillingRefund,
                AdminPermission::BillingReconcile,
                AdminPermission::AuditView,
            ],
            AdminRoleCode::SeoManager => [
                AdminPermission::DashboardView,
                AdminPermission::ContentView,
                AdminPermission::SearchView,
                AdminPermission::SeoManage,
                AdminPermission::RedirectsManage,
            ],
            AdminRoleCode::SystemOperator => [
                AdminPermission::DashboardView,
                AdminPermission::ImportsExecute,
                AdminPermission::CacheView,
                AdminPermission::CacheInvalidate,
                AdminPermission::SearchView,
                AdminPermission::SearchReindex,
                AdminPermission::SettingsView,
                AdminPermission::OperationsView,
                AdminPermission::OperationsExecute,
                AdminPermission::AuditView,
            ],
            AdminRoleCode::ReadOnlyAuditor => [
                AdminPermission::DashboardView,
                AdminPermission::AdministratorsView,
                AdminPermission::UsersView,
                AdminPermission::ContentView,
                AdminPermission::PremiumView,
                AdminPermission::AuditView,
                AdminPermission::OperationsView,
            ],
        };

        return array_values(array_unique([
            AdminPermission::AdministrationAccess,
            ...$permissions,
        ], SORT_REGULAR));
    }

    /** @return array<string, AdminPermission> */
    public function legacyGatePermissions(): array
    {
        return [
            'manage-seasonvar-imports' => AdminPermission::ImportsExecute,
            'manage-catalog' => AdminPermission::ContentManage,
            'manage-comments' => AdminPermission::CommentsModerate,
            'manage-reviews' => AdminPermission::ReviewsModerate,
            'manage-content-requests' => AdminPermission::RequestsModerate,
            'manage-technical-issues' => AdminPermission::TicketsSupport,
            'manage-release-calendar' => AdminPermission::CalendarManage,
            'manage-help-center' => AdminPermission::HelpManage,
            'view-premium-administration' => AdminPermission::PremiumView,
            'manage-premium-grants' => AdminPermission::PremiumGrant,
            'manage-premium-promotions' => AdminPermission::PremiumPromotions,
            'view-premium-billing-audit' => AdminPermission::BillingView,
            'reconcile-premium' => AdminPermission::BillingReconcile,
        ];
    }
}
