<div class="mx-auto max-w-5xl space-y-5">
    <header class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel sm:p-6">
        <div class="flex min-w-0 flex-wrap items-start justify-between gap-4">
            <div class="min-w-0"><div class="flex flex-wrap gap-2 text-xs font-bold"><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-emerald-800">{{ $request->card->typeLabel }}</span><span title="{{ $request->card->statusDescription }}" class="rounded-full bg-slate-100 px-2.5 py-1 text-slate-700">{{ $request->card->statusLabel }}</span></div><h1 class="mt-3 break-words text-2xl font-black text-slate-800 sm:text-3xl">{{ $request->card->title }}</h1>@if ($request->card->originalTitle)<p class="mt-1 break-words text-sm text-slate-500">{{ $request->card->originalTitle }}</p>@endif</div>
            <div class="flex flex-wrap gap-2">
                @if ($isAuthenticated)
                    <button type="button" wire:click="setVote({{ $request->card->hasVoted ? 'false' : 'true' }})" wire:loading.attr="disabled" wire:target="setVote" @disabled(! $request->card->canEngage) aria-pressed="{{ $request->card->hasVoted ? 'true' : 'false' }}" class="inline-flex min-h-11 items-center gap-2 rounded-control px-4 py-2 text-sm font-bold {{ $request->card->hasVoted ? 'bg-emerald-700 text-white' : 'bg-slate-100 text-slate-700' }} disabled:opacity-50"><x-ui.icon name="fa-solid fa-arrow-up" />{{ $request->card->hasVoted ? __('requests.actions.remove_vote') : __('requests.actions.vote') }} · {{ $request->card->votes }}</button>
                    <button type="button" wire:click="setFollow({{ $request->card->isFollowing ? 'false' : 'true' }})" wire:loading.attr="disabled" wire:target="setFollow" @disabled(! $request->card->canEngage) aria-pressed="{{ $request->card->isFollowing ? 'true' : 'false' }}" class="inline-flex min-h-11 items-center gap-2 rounded-control px-4 py-2 text-sm font-bold {{ $request->card->isFollowing ? 'bg-sky-700 text-white' : 'bg-slate-100 text-slate-700' }} disabled:opacity-50"><x-ui.icon name="fa-solid fa-bell" />{{ $request->card->isFollowing ? __('requests.actions.unfollow') : __('requests.actions.follow') }}</button>
                @else
                    <a href="{{ $loginUrl }}" class="inline-flex min-h-11 items-center rounded-control bg-emerald-700 px-4 py-2 text-sm font-bold text-white">{{ __('requests.actions.login_to_participate') }}</a>
                @endif
            </div>
        </div>
    </header>

    @if ($statusMessage)<p role="status" aria-live="polite" class="rounded-control bg-emerald-50 p-4 text-sm font-bold text-emerald-800">{{ $statusMessage }}</p>@endif
    @if ($actionError)<p role="alert" class="rounded-control bg-rose-50 p-4 text-sm font-bold text-rose-800">{{ $actionError }}</p>@endif
    <div wire:loading.delay role="status" aria-live="polite" class="rounded-control bg-sky-50 p-3 text-sm font-bold text-sky-700">{{ __('requests.states.updating') }}</div>

    <x-ui.panel :title="__('requests.detail.requested_content')" icon="fa-solid fa-circle-info">
        <dl class="grid gap-4 sm:grid-cols-2">
            <div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.type') }}</dt><dd class="mt-1 text-slate-800">{{ $request->card->typeLabel }}</dd></div>
            @if ($request->card->targetLabel)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.target') }}</dt><dd class="mt-1">@if ($request->card->targetUrl)<a href="{{ $request->card->targetUrl }}" class="font-bold text-emerald-700">{{ $request->card->targetLabel }}</a>@else{{ $request->card->targetLabel }}@endif</dd></div>@endif
            @if ($request->card->year)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.release_year') }}</dt><dd class="mt-1 text-slate-800">{{ $request->card->year }}</dd></div>@endif
            @if ($request->alternativeTitle)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.alternative_title') }}</dt><dd class="mt-1 break-words text-slate-800">{{ $request->alternativeTitle }}</dd></div>@endif
            @if ($request->country)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.country') }}</dt><dd class="mt-1 text-slate-800">{{ $request->country }}</dd></div>@endif
            @if ($request->seasonNumber !== null)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.season_number') }}</dt><dd class="mt-1 text-slate-800">{{ $request->seasonNumber }}</dd></div>@endif
            @if ($request->episodeNumber !== null)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.episode_number') }}</dt><dd class="mt-1 text-slate-800">{{ $request->episodeNumber }}</dd></div>@endif
            @if ($request->audioLanguage)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.audio_language') }}</dt><dd class="mt-1 text-slate-800">{{ __('requests.languages.'.$request->audioLanguage) }}</dd></div>@endif
            @if ($request->subtitleLanguage)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.subtitle_language') }}</dt><dd class="mt-1 text-slate-800">{{ __('requests.languages.'.$request->subtitleLanguage) }}</dd></div>@endif
            @if ($request->requestedQuality)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.requested_quality') }}</dt><dd class="mt-1 text-slate-800">{{ $request->requestedQuality }}</dd></div>@endif
            @if ($request->correctionField)<div><dt class="text-xs font-bold uppercase tracking-wide text-slate-500">{{ __('requests.fields.correction_field') }}</dt><dd class="mt-1 text-slate-800">{{ __('requests.correction_fields.'.$request->correctionField) }}</dd></div>@endif
        </dl>
        @if ($request->explanation)<div class="mt-5 border-t border-slate-100 pt-4"><h2 class="text-sm font-black text-slate-700">{{ __('requests.fields.explanation') }}</h2><p class="mt-2 whitespace-pre-wrap break-words text-sm leading-6 text-slate-700">{{ $request->explanation }}</p></div>@endif
        @if ($request->currentValue || $request->proposedValue)<div class="mt-5 grid gap-4 border-t border-slate-100 pt-4 sm:grid-cols-2">@if ($request->currentValue)<div><h2 class="text-sm font-black text-slate-700">{{ __('requests.fields.current_value') }}</h2><p class="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{{ $request->currentValue }}</p></div>@endif @if ($request->proposedValue)<div><h2 class="text-sm font-black text-slate-700">{{ __('requests.fields.proposed_value') }}</h2><p class="mt-2 whitespace-pre-wrap break-words text-sm text-slate-600">{{ $request->proposedValue }}</p></div>@endif</div>@endif
        @if ($request->publicNote)<div class="mt-5 rounded-control bg-sky-50 p-4 text-sm text-sky-900"><strong>{{ __('requests.fields.public_update') }}</strong><p class="mt-1 whitespace-pre-wrap break-words">{{ $request->publicNote }}</p></div>@endif
        @if ($request->rejectionReason)<div class="mt-5 rounded-control bg-amber-50 p-4 text-sm text-amber-900"><strong>{{ __('requests.fields.rejection_reason') }}:</strong> {{ $request->rejectionReason }}</div>@endif
        @if ($request->completionUrl)<a href="{{ $request->completionUrl }}" class="mt-5 inline-flex min-h-11 items-center gap-2 rounded-control bg-emerald-700 px-4 py-2 text-sm font-bold text-white"><x-ui.icon name="fa-solid fa-circle-check" />{{ __('requests.actions.open_result') }}: {{ $request->completionLabel }}</a>@endif
    </x-ui.panel>

    @if (count($request->sourceLinks) > 0 || count($request->externalIdentifiers) > 0)
        <x-ui.panel :title="__('requests.detail.references')" icon="fa-solid fa-link"><ul class="space-y-2">@foreach ($request->sourceLinks as $link)<li><a href="{{ $link['url'] }}" target="_blank" rel="nofollow noopener noreferrer" class="inline-flex min-h-11 max-w-full items-center gap-2 break-all font-bold text-emerald-700"><x-ui.icon name="fa-solid fa-arrow-up-right-from-square" />{{ $link['label'] }}</a></li>@endforeach @foreach ($request->externalIdentifiers as $identifier)<li class="break-words text-sm text-slate-700"><strong>{{ $identifier['label'] }}:</strong> @if ($identifier['url'])<a href="{{ $identifier['url'] }}" target="_blank" rel="nofollow noopener noreferrer" class="font-bold text-emerald-700">{{ $identifier['identifier'] }}</a>@else{{ $identifier['identifier'] }}@endif</li>@endforeach</ul></x-ui.panel>
    @endif

    <x-ui.panel :title="__('requests.detail.timeline')" icon="fa-solid fa-clock-rotate-left"><ol class="space-y-4">@foreach ($request->history as $entry)<li class="border-l-2 border-emerald-200 pl-4"><div class="flex flex-wrap items-center justify-between gap-2"><strong class="text-sm text-slate-800">{{ $entry['label'] }}</strong><time class="text-xs text-slate-500">{{ $entry['date'] }}</time></div>@if ($entry['reason'])<p class="mt-1 whitespace-pre-wrap break-words text-sm text-slate-600">{{ $entry['reason'] }}</p>@endif</li>@endforeach</ol></x-ui.panel>

    @if (count($request->clarifications) > 0 || $request->canClarify)
        <x-ui.panel :title="__('requests.clarifications.title')" icon="fa-solid fa-comments"><div class="space-y-3">@foreach ($request->clarifications as $message)<article class="rounded-control bg-slate-50 p-3"><div class="flex justify-between gap-3 text-xs font-bold text-slate-500"><span>{{ $message['role_label'] }}</span><time>{{ $message['date'] }}</time></div><p class="mt-2 whitespace-pre-wrap break-words text-sm text-slate-700">{{ $message['body'] }}</p></article>@endforeach</div>@if ($request->canClarify)<form wire:submit="clarify" class="mt-4"><label for="clarification-body" class="block text-sm font-bold text-slate-700">{{ __('requests.clarifications.reply_label') }}</label><textarea id="clarification-body" wire:model="clarificationBody" rows="4" class="mt-2 w-full rounded-control border border-slate-300 p-3"></textarea><button type="submit" wire:loading.attr="disabled" wire:target="clarify" class="mt-3 min-h-11 rounded-control bg-emerald-700 px-4 py-2 text-sm font-bold text-white">{{ __('requests.actions.send_clarification') }}</button></form>@endif</x-ui.panel>
    @endif

    @if ($request->canEdit)
        <x-ui.panel :title="__('requests.detail.edit_title')" icon="fa-solid fa-pen"><form wire:submit="save" class="space-y-4"><x-form.field :label="__('requests.fields.alternative_title')" for="edit-alternative-title" wire:model="alternativeTitle" /><div><label for="edit-explanation" class="block text-sm font-bold text-slate-700">{{ __('requests.fields.explanation') }}</label><textarea id="edit-explanation" wire:model="explanation" rows="4" class="mt-2 w-full rounded-control border border-slate-300 p-3"></textarea></div><div class="grid gap-4 sm:grid-cols-2"><div><label for="edit-audio" class="block text-sm font-bold text-slate-700">{{ __('requests.fields.audio_language') }}</label><select id="edit-audio" wire:model="audioLanguage" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3"><option value="">{{ __('requests.fields.not_specified') }}</option>@foreach ($languageOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div><div><label for="edit-subtitles" class="block text-sm font-bold text-slate-700">{{ __('requests.fields.subtitle_language') }}</label><select id="edit-subtitles" wire:model="subtitleLanguage" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3"><option value="">{{ __('requests.fields.not_specified') }}</option>@foreach ($languageOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div></div><x-form.field :label="__('requests.fields.additional_source')" for="edit-source" type="url" wire:model="sourceLinks.0" /><button type="submit" wire:loading.attr="disabled" wire:target="save" class="min-h-11 rounded-control bg-slate-800 px-4 py-2 text-sm font-bold text-white">{{ __('requests.actions.save') }}</button></form></x-ui.panel>
    @endif

    @if ($request->canWithdraw)
        <section class="rounded-panel border border-rose-200 bg-white p-5 shadow-panel"><h2 class="font-black text-slate-800">{{ __('requests.detail.withdraw_title') }}</h2><p class="mt-2 text-sm text-slate-600">{{ __('requests.detail.withdraw_notice') }}</p><button type="button" wire:click="withdraw" wire:confirm="{{ __('requests.confirmations.withdraw') }}" class="mt-4 min-h-11 rounded-control bg-rose-700 px-4 py-2 text-sm font-bold text-white">{{ __('requests.actions.withdraw') }}</button></section>
    @endif
</div>
