<div class="space-y-5">
    <header class="rounded-panel border border-slate-200 bg-white p-5 shadow-panel sm:p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div><h1 class="text-2xl font-black text-slate-800 sm:text-3xl">{{ __('requests.mine.title') }}</h1><p class="mt-2 text-sm text-slate-600">{{ __('requests.mine.description') }}</p></div><a href="{{ $createUrl }}" class="inline-flex min-h-11 items-center gap-2 rounded-control bg-emerald-700 px-4 py-2 text-sm font-bold text-white"><x-ui.icon name="fa-solid fa-plus" />{{ __('requests.actions.create') }}</a></div></header>
    <x-ui.panel :title="__('requests.directory.filters_title')" icon="fa-solid fa-filter"><div class="grid gap-4 md:grid-cols-3"><div><label for="my-scope" class="block text-sm font-bold text-slate-700">{{ __('requests.mine.scope') }}</label><select id="my-scope" wire:model.live="scope" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2">@foreach ($scopeOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div><div><label for="my-status" class="block text-sm font-bold text-slate-700">{{ __('requests.fields.status') }}</label><select id="my-status" wire:model.live="status" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2"><option value="">{{ __('requests.filters.all_statuses') }}</option>@foreach ($statusOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div><div><label for="my-sort" class="block text-sm font-bold text-slate-700">{{ __('requests.fields.sort') }}</label><select id="my-sort" wire:model.live="sort" class="mt-2 min-h-11 w-full rounded-control border border-slate-300 px-3 py-2">@foreach ($sortOptions as $option)<option value="{{ $option['value'] }}">{{ $option['label'] }}</option>@endforeach</select></div></div></x-ui.panel>
    <div wire:loading.delay wire:target="scope,status,sort" role="status" class="rounded-control bg-sky-50 p-3 text-sm font-bold text-sky-700">{{ __('requests.states.loading') }}</div>
    @island(name: 'my-content-requests-pagination', always: true, with: $this->paginationIslandPage)
    <x-ui.pagination-region name="my-content-requests-results">
    @if (! $schemaReady)<x-ui.panel><p>{{ __('requests.states.unavailable') }}</p></x-ui.panel>@elseif ($requests->isEmpty())<x-ui.panel><div class="py-6 text-center"><h2 class="font-black text-slate-700">{{ __('requests.mine.empty') }}</h2><a href="{{ $createUrl }}" class="mt-4 inline-flex min-h-11 items-center rounded-control bg-emerald-700 px-4 py-2 text-sm font-bold text-white">{{ __('requests.actions.create') }}</a></div></x-ui.panel>@else<section class="grid gap-4 lg:grid-cols-2">@foreach ($requests as $request)<x-content-requests.card :request="$request" />@endforeach</section><nav aria-label="{{ __('requests.fields.pagination') }}">{{ $requests->links(data: ['region' => 'my-content-requests-results']) }}</nav>@endif
    </x-ui.pagination-region>
    @endisland
</div>
